# Site settings
title: Kaldalón
email: johann@kaldalon.is
url: http://kaldalon.is
baseurl: 
description: "Þróun og umsjón fasteignaverkefna"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#0a0a0a'
  links: '#219ab3'
  bg-light: '#dddddd'

# Footer settings
footer: Kaldalón ehf.
ssn: Kt. 531009 0610

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:

# Build settings
markdown: kramdown
permalink: pretty
